# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField()),
                ('result_dt', models.DateTimeField(verbose_name='result date')),
                ('result_type', models.CharField(max_length=200)),
                ('result_val', models.CharField(max_length=200)),
            ],
        ),
    ]
