# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redcap_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField()),
                ('project_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mrn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(max_length=200)),
                ('mrn_type', models.CharField(choices=[('P', 'EPIC'), ('M', 'MEDIPAC'), ('E', 'EMPI')], max_length=1)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redcap_rest.Identity')),
            ],
        ),
    ]
